version: '2'

services:
  express_server:
    build:
      context: bad-rest-api
    container_name: express_server
    image: express_server
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/usr/src/app
  
  falco:
    container_name: falco
    image: sysdig/falco:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - ${PWD}/falco_rules.yaml:/etc/falco_rules.yaml
    tty: true
